// <auto-generated />
using System;
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnimalBreed")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AnimalName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AnimalSpecies")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Availability")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AnimalBreed = "Unknown",
                            AnimalName = "Yanaba",
                            AnimalSpecies = "Polar Bear",
                            Availability = true,
                            DateCreated = new DateTime(2022, 8, 19, 13, 1, 7, 679, DateTimeKind.Local).AddTicks(7090),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Afraid of shoes",
                            UserId = 4
                        },
                        new
                        {
                            AnimalId = 2,
                            AnimalBreed = "Unknown",
                            AnimalName = "Meg",
                            AnimalSpecies = "Giant Panda",
                            Availability = true,
                            DateCreated = new DateTime(2022, 8, 19, 13, 1, 7, 679, DateTimeKind.Local).AddTicks(9810),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Toilet trained",
                            UserId = 3
                        },
                        new
                        {
                            AnimalId = 3,
                            AnimalBreed = "Unknown",
                            AnimalName = "Goldie",
                            AnimalSpecies = "Amur Leopard",
                            Availability = true,
                            DateCreated = new DateTime(2022, 8, 19, 13, 1, 7, 679, DateTimeKind.Local).AddTicks(9820),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Can't sit still",
                            UserId = 3
                        },
                        new
                        {
                            AnimalId = 4,
                            AnimalBreed = "Unknown",
                            AnimalName = "Kendrick",
                            AnimalSpecies = "Orangutan",
                            Availability = true,
                            DateCreated = new DateTime(2022, 8, 19, 13, 1, 7, 679, DateTimeKind.Local).AddTicks(9830),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Really messy roommate",
                            UserId = 2
                        },
                        new
                        {
                            AnimalId = 5,
                            AnimalBreed = "Unknown",
                            AnimalName = "Angie",
                            AnimalSpecies = "Sea Turtle",
                            Availability = true,
                            DateCreated = new DateTime(2022, 8, 19, 13, 1, 7, 679, DateTimeKind.Local).AddTicks(9830),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thinks they're a cat",
                            UserId = 1
                        },
                        new
                        {
                            AnimalId = 6,
                            AnimalBreed = "Unknown",
                            AnimalName = "Theodore",
                            AnimalSpecies = "Chimpanzee",
                            Availability = true,
                            DateCreated = new DateTime(2022, 8, 19, 13, 1, 7, 679, DateTimeKind.Local).AddTicks(9840),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Good snuggles",
                            UserId = 4
                        },
                        new
                        {
                            AnimalId = 7,
                            AnimalBreed = "Unknown",
                            AnimalName = "Eggy",
                            AnimalSpecies = "Elephant",
                            Availability = false,
                            DateCreated = new DateTime(2022, 8, 19, 13, 1, 7, 679, DateTimeKind.Local).AddTicks(9840),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Demands to sleep in bed with humans",
                            UserId = 1
                        },
                        new
                        {
                            AnimalId = 8,
                            AnimalBreed = "Unknown",
                            AnimalName = "Gerald",
                            AnimalSpecies = "Plains Bison",
                            Availability = false,
                            DateCreated = new DateTime(2022, 8, 19, 13, 1, 7, 679, DateTimeKind.Local).AddTicks(9840),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Loves giving wet kisses",
                            UserId = 5
                        },
                        new
                        {
                            AnimalId = 9,
                            AnimalBreed = "Unknown",
                            AnimalName = "Gavr",
                            AnimalSpecies = "Vaquita",
                            Availability = false,
                            DateCreated = new DateTime(2022, 8, 19, 13, 1, 7, 679, DateTimeKind.Local).AddTicks(9850),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "1 of 10 left in the world",
                            UserId = 6
                        },
                        new
                        {
                            AnimalId = 10,
                            AnimalBreed = "Unknown",
                            AnimalName = "Wagyu",
                            AnimalSpecies = "Rhino",
                            Availability = false,
                            DateCreated = new DateTime(2022, 8, 19, 13, 1, 7, 679, DateTimeKind.Local).AddTicks(9850),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Loves to nuzzle",
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
